name: coka
description: Coka Mobile App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+22

environment:
  sdk: ">=2.19.4 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  localization: ^2.1.0
  google_fonts: ^6.1.0
  flutter_facebook_auth: ^6.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.7.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.4
  pin_code_fields: ^8.0.1
  flutter_spinkit: ^5.1.0
  double_back_to_close_app: ^2.1.0
  flutter_rating_bar: ^4.0.1
  awesome_dialog: ^3.0.2
  flutter_contacts: ^1.1.6
  sip_ua: ^1.0.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.0
  flutter_webrtc: ^0.12.2
  dio: ^5.1.1
  dropdown_search: ^6.0.1
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.10
  flutter_inappwebview: ^6.1.5
  flutter_linkify: ^6.0.0
  firebase_database: ^10.1.0
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.1
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  device_info_plus: ^9.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_speed_dial: ^7.0.0
  file_picker: ^8.1.2
  shimmer: ^3.0.0
  http_parser: ^4.0.2
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_charts: ^28.2.7
  sign_in_with_apple: ^7.0.1
  badges: ^3.1.2
  avatar_stack: ^1.2.0
  cached_network_image: ^3.3.0
  firebase_analytics: ^10.7.2
  flutter_animate: ^4.2.0+1
  animated_text_kit: ^4.2.2
  package_info_plus: ^8.1.1
  flutter_html_audio: ^3.0.0-beta.2
  in_app_review: ^2.0.11
  flutter_overlay_window: ^0.4.3
  # device_apps: ^2.2.0
  gap: ^3.0.1
  rive: ^0.13.4
  upgrader: ^10.3.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - shorebird.yaml
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

dependency_overrides:
  web: ^1.0.0
